services:
  bot:
    build: ./bot/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      TRACKING_SERVER_URL: http://server:4000
  server:
    build: ./server/
    ports:
      - "4000:4000"
